name: 'Add Project'

on:
  workflow_dispatch:
    inputs:
      git_url:
        description: "URL of repository to add"
        required: true
        default: ''

jobs:
  add_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      
      - name: Set up git
        run: |
          git config --local user.email "mail@jonathan-treffler.de"
          git config --local user.name "Jonathan Treffler"
          git config pull.rebase false
          git pull

      - name: Add Project
        run: sh add_project.sh ${{ github.event.inputs.git_url }}
        
      - name: Commit changes
        continue-on-error: true
        run: |
          git pull
          git add -A
          
          user=$(echo ${{ github.event.inputs.git_url }} | cut -d'/' -f 4)
          repository=$(echo ${{ github.event.inputs.git_url }} | cut -d'/' -f 5)
          
          git commit -m "Added Project $user/$repository" -a
          
          git log
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
