name: SCC

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  calculate_loc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git config pull.rebase false
          git pull
          git submodule update --recursive --remote
      
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
            
      - name: SCC install
        run: go get -u github.com/boyter/scc/
      
      - name: SCC
        run: scc ./projects/ > scc.txt
      
      - name: SCC html
        run: scc ./projects/ --include-ext vue,js,py,pde,css,sh,html,php,ts,cpp,json,xml,md -f html-table > scc.html
      
      - name: README update
        run: node scc.js
      
      - name: Delete temporary files
        run: rm scc.html
      
      - name: Commit files
        continue-on-error: true
        run: |
          git pull
          git add -A
          git commit -m "Updated Readme scc" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
