name: SCC

on:
  workflow_dispatch:

jobs:
  calculate_loc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
            
      - name: scc install
        run: go get -u github.com/boyter/scc/
      
      - name: scc
        run: scc ./projects/ &> scc.txt
      
      - name: scc html
        run: scc ./projects/ -f html-table --no-complexity &> scc.html
      
      - name: README update
        run: node scc.js
    
      - name: Upload scc output as a build artifact
        uses: actions/upload-artifact@v1
        with:
          name: scc
          path: scc.txt
      
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git pull
          git add -A
          git commit -m "Updated Readme scc" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
